project:
  type: website
  output-dir: docs

website:
  title: "dmbarnas_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About Me
        href: about.qmd
      - text: Research
        href: research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

