---
title: "Welcome!"
---

!(Profile_image)\[images/Profile_image.jpg\]

I am an early career field researcher and data analyst in my final year as an MS candidate in the Biology Department at CSU Northridge. Current research focuses on the impact of natural environmental gradients (i.e. submarine groundwater discharge, SGD) on coastal coral reef biodiversity and ecosystem functioning. I aim to assess the relationship of species and functional trait diversity along an SGD gradient of two coral reefs in Mo'orea, French Polynesia, as well as understand the physiological effects of SGD on multiple benthic taxa and assemblages of varying species and functional identities in high and low SGD influence.

Previous work has focused on marine ecological shifts in response to climate change and restoration techniques of coral reef ecosystems. After receiving my BA in Marine Science from the University of San Diego in 2015, I spent three years in the Florida Keys working with local environmental organizations (i.e. Coral Restoration Foundation, Mote Marine Laboratory, and Florida Fish and Wildlife Conservation Commission) to monitor and restore threatened or damaged reefs, as well as study effects of climate change on those ecosystems. I began working at CSUN in 2018 as a Research Technician in Dr. Nyssa Silbiger's lab before being accepted into her lab in 2021 as a graduate student.

As a technician and graduate student, I have worked primarily in R to develop protocols and training materials for lab equipment and procedures. I have created scripts and an R packages for cleaning, processing, and analyzing data from *in situ* environmental parameter loggers and other lab and field data collections, all still used by current lab members. I have also worked in R Shiny to simplify processing and visualizing data from multiple Onset HOBO loggers (Conductivity-Temperature, pH, and Water Level). I am currently enrolled in a professional data analytics certification program, where I am gaining experience in SQL and Tableau.

\
\## Contact

Github: (dbarnas)\[https://github.com/dbarnas\]

Email: danielle.barnas\@csun.edu

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r, echo = F, eval = F}
1 + 1
```
