---
title: "Research Interests"
---

## MS Biology ongoing thesis projects at California State University, Northridge (Advisor: Dr. Nyssa J. Silbiger)

#### Barnas, D.M.\*, Zeff, M., Silbiger, N.J. _(In Progress)_. Natural environmental gradients alter community composition and functional diversity on coral reefs.  

GitHub Repository can be found [HERE](https://github.com/dbarnas/Community_Functional_Diversity)

#### Barnas, D.M.\*, Zeff, M., Silbiger, N.J. _(In Progress)_. Functional diversity of coral reef communities drives changes in ecosystem functioning.  

GitHub Repository can be found [HERE](https://github.com/dbarnas/BEF_FunctionalDiv)


## Additonal projects (Assisted as a research technician at CSUN)

#### Becker, D.M. and Silbiger, N.J. 2020. Nutrient and sediment loading affect multiple facets of functionality in a tropical branching coral. Journal of Experimental Biology 223.

#### Fields, J.B. and Silbiger, N.J. 2022. Foundation species loss alters multiple ecosystem functions within temperate tidepool communities. Marine Science Progress Series 683.

#### Kerlin, J.R., Barnas, D.M.\*, Silbiger, N.J. _In Progress (anticiipated 2023)_. Effects of submarine groundwater discharge and coral-coral interactions on common coral species, _Porites rus_.

#### Chiachi, A., Barnas, D.M.\*, Silbiger, N.J. _In Progress (anticiipated 2023)_. Determining the effects of marine heatwaves on red abalone, _Haliotis rufescens_, across multiple size classes.


## Other reserach interests

- Coral reef conservation and restoration  
- Temporal changes of marine ecosystems due to disturbance events or climage change  
- Functional traits as key drivers of BEF relationships  
- Climate change impacts to organismal and community physiology  
- Impacts of natural processes (i.e. submarine groundwater discharge) on organismal and community physiology  

